### ISSUE TITLE
Cannot configure bucket with server side encryption to ALB or NLB

### ISSUE THREAD

**Issue by beingamarnath** [cloudposse/terraform-aws-lb-s3-bucket#9]
S3 bucket created with this module cannot be configured to ALB or NLB as it throws error as specified here. 
https://github.com/terraform-aws-modules/terraform-aws-alb/issues/61

Any insights on how this works for you?

**Comment by anarwal** [comment]
I used the policy given here: https://www.terraform.io/docs/providers/aws/d/elb_service_account.html
for both NLB and ALB s3 buckets however I am still having same problem (access denied) with NLB. 

I have it working with ALB (without turning encryption off) but NLB still needs encryption turned off. I am not in favor of turning encryption of for s3 buckets. Is there a fix for this?

**Comment by Grasume** [comment]
I would have to agree and having this same Issue. We have S3 buckets forced to have encryption from the Root account.

**Comment by carthewd** [comment]
You'll hit this if forcing encryption for the whole bucket using SSE-KMS in the bucket policy - the ALB service/access logs make use of SSE-S3 (S3 managed SSE). The documentation mentions this (a little indirectly): https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html

So you can still enforce encryption in the bucket policy by using `AES256` for sse_algorithm instead of `aws:kms` or however granular you want to go (with the caveat that you'll be using S3-managed encryption). 

Objects encrypted using SSE-S3 will show up as `Encryption:AES256` as mentioned in the linked issue.

**Comment by deadlysyn** [comment]
Started working on a PR for https://github.com/cloudposse/terraform-aws-nlb to re-enable logging. @carthewd's advice makes sense per the docs, but despite https://github.com/cloudposse/terraform-aws-s3-log-storage seeming to have the right defaults for server side encryption, it still gives validation error due to access being denied to the log bucket.

Tried manual tests with `sse_algorithm = AES256` and `kms_master_key_id = null` or omitted entirely (going out on a limb since the module default it to the empty string), same behavior with each approach.

I am missing something.

**Comment by deadlysyn** [comment]
If no one else has ideas at the ready, I'll try and do more testing and hopefully find the right incantation as part of Hactoberfest.  :-)  When I last looked, it really seemed the upstream dependencies had already exposed knobs to make this go away...but pulling in those changes didn't neatly resolve it as expected.

**Comment by jwstric2** [comment]
@deadlysyn  It appears to also be an issue with the actual policies.  See https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-access-logs.html#attach-bucket-policy

My private fork looks like the below:

```
data "aws_iam_policy_document" "default" {
  count = var.enabled ? 1 : 0

  statement {
    sid = "ELBAWSPut"

    principals {
      type        = "AWS"
      identifiers = [join("", data.aws_elb_service_account.default.*.arn)]
    }

    effect = "Allow"

    actions = [
      "s3:PutObject",
      "s3:GetObject"
    ]

    resources = [
      "arn:aws:s3:::${module.access_bucket_label.id}/*",
    ]
  }

  statement {
    sid = "AWSLogDeliveryWrite"

    principals {
      type        = "Service"
      identifiers = ["delivery.logs.amazonaws.com"]
    }

    effect = "Allow"

    actions = [
      "s3:PutObject"
    ]

    resources = [
      "arn:aws:s3:::${module.access_bucket_label.id}/*",
    ]
  }

  statement {
    sid = "AWSLogDeliveryAclCheck"

    principals {
      type        = "Service"
      identifiers = ["delivery.logs.amazonaws.com"]
    }

    effect = "Allow"

    actions = [
      "s3:GetBucketAcl"
    ]

    resources = [
      "arn:aws:s3:::${module.access_bucket_label.id}",
    ]
  }

}
```

Still have to confirm functionality but at least I don't get the same error as described below:

```
module.nlb.module.access_logs.aws_s3_bucket.default[0]: Modifying... 
module.nlb.module.access_logs.aws_s3_bucket.default[0]: Modifications complete after 5s
module.nlb.aws_lb.default: Creating...
module.nlb.aws_lb.default: Still creating... [10s elapsed]
module.nlb.aws_lb.default: Still creating... [20s elapsed]
module.nlb.aws_lb.default: Still creating... [30s elapsed]
module.nlb.aws_lb.default: Still creating... [40s elapsed]
module.nlb.aws_lb.default: Still creating... [50s elapsed]
module.nlb.aws_lb.default: Still creating... [1m0s elapsed]
module.nlb.aws_lb.default: Still creating... [1m10s elapsed]
module.nlb.aws_lb.default: Still creating... [1m20s elapsed]
module.nlb.aws_lb.default: Still creating... [1m30s elapsed]
module.nlb.aws_lb.default: Still creating... [1m40s elapsed]
module.nlb.aws_lb.default: Still creating... [1m50s elapsed]
module.nlb.aws_lb.default: Still creating... [2m0s elapsed]
module.nlb.aws_lb.default: Still creating... [2m10s elapsed]
module.nlb.aws_lb.default: Still creating... [2m20s elapsed]
module.nlb.aws_lb.default: Still creating... [2m30s elapsed]
module.nlb.aws_lb.default: Still creating... [2m40s elapsed]
module.nlb.aws_lb.default: Still creating... [2m50s elapsed]
module.nlb.aws_lb.default: Creation complete after 2m57s ....

Apply complete! Resources: 1 added, 1 changed, 1 destroyed.
Releasing state lock. This may take a few moments...

```
